apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
    company: acme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
      company: acme
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
        company: acme
    spec:
      containers:
      - name: app
        image: localhost:32000/app:.TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  externalIPs:
  - 192.168.56.10
  selector:
    app: app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9000
      name: http
